### PR TITLE
Giving complete functionality

### PR DESCRIPTION
**Pull request by robinbenitezmora**
This special project bring as new thing that the users will be able to interact with the app by searching their favorites movies, reading comments and adding 'likes'. It is an important information source for the cinephiles and general public.

### CODE REVIEW

**Review by DeliceLydia — COMMENTED** [review]
## Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that did not follow the requirements, you should merge your `feature` branch to the `development` branch and open a PR from there

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by armandocomellas1** [comment]
> ## Hi Team,
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> ## Invalid Code Review Request
> You have submitted a project, that did not follow the requirements, you should merge your `feature` branch to the `development` branch and open a PR from there
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> 
> ### Cheers and Happy coding!👏👏👏
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._

OK we are using the same pull request

**Review by tresorsawasawa — COMMENTED** [review]
# STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @ ,:wave: :wave: 
While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🛑 🛑

You have submitted a project that doesn't follow the use of GitFlow. As mentioned in the previous review, kindly make sure you create your **Pull Request** from the `dev` branch to the `main` branch and not from the feature branch `robin-part` to `dev`. For more details I suggest you read **[this article](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md)**

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

---
Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

---
_Invalid Code Review Request **Does not count** into the code reviews limit._

**Comment by armandocomellas1** [comment]
To be honest l dont understand what you want guys,

 

I know exactly what is a gitflow, l créate a development Branch l set it as default instead main, then l créate my feature Branch where l Will working on and then l pull request feature Branch created vs develpment, so what is the problema?

 

Thank you guys.

 

De: Tresor Sawasawa ***@***.***> 
Enviado el: sábado, 3 de septiembre de 2022 09:27 a. m.
Para: armandocomellas1/group-kanban ***@***.***>
CC: Armando Comellas ***@***.***>; Comment ***@***.***>
Asunto: Re: [armandocomellas1/group-kanban] Giving complete functionality (PR #26)

 

@tresorsawasawa commented on this pull request.


STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑


Hi @ ,👋 👋
While you made a great effort in this project, unfortunately, I cannot proceed to review your code.


Invalid Code Review Request 🛑 🛑


You have submitted a project that doesn't follow the use of GitFlow. As mentioned in the previous review, kindly make sure you create your Pull Request from the dev branch to the main branch and not from the feature branch robin-part to dev. For more details I suggest you read this article <https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md> 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

  _____  

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @tresorsawasawa <https://github.com/tresorsawasawa>  when you comment so I can receive the notification or use slack with the same name.

  _____  

Invalid Code Review Request Does not count into the code reviews limit.

**Comment by tresorsawasawa** [comment]
Hi @armandocomellas1 

In short, the pull request to be submitted should be created from the `dev` branch to the `main`

I think this is clear

**Pull request merged**
